name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 10.1.0
repository: https://github.com/tlserver/flutter_map_location_marker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.0
  flutter_rotation_sensor: ^0.1.0
  geolocator: ^14.0.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
