name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 4.0.1+1
homepage: https://github.com/tlserver/flutter_map_location_marker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_map: ^1.1.0
  geolocator: ^8.2.1
  latlong2: ^0.8.1

dev_dependencies:
  flutter_joystick: ^0.0.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
