name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 2.1.0
homepage: https://github.com/tlserver/flutter_map_location_marker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_map: ^0.14.0
  geolocator: ^8.0.5
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
