name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 1.0.0-nullsafety.0
homepage: https://github.com/tlserver/flutter_map_location_marker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.6.0
  flutter_map: ^0.13.1
  geolocator: ^7.1.0
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
